name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-versions: ['3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python for ${{ matrix.python-versions }}
        uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-versions }}


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flask_microblog:$(date +%s)
